### ISSUE TITLE
Deleting library or changing visibility does not update v3 database

### ISSUE THREAD

**Issue by olli-suutari-jkl** [libraries-fi/kirkanta-api#2]
Deleting a library or changing it's visibility does not delete it or update the visibility to the database of V3. These changes were made early in December, but the library is still available via V3 api.

https://api.kirjastot.fi/v3/library/86605
https://hakemisto.kirjastot.fi/jyvaskyla/testikirjasto-jyvaskyla

![image](https://user-images.githubusercontent.com/42733913/50584317-81050e00-0e77-11e9-88fc-dce0668f48ac.png)

**Comment by sjuvonen** [comment]
It seems quite a lot of work because there are three different databases involved, with further complications due to how the data is transferred between current and legacy Kirkanta (for legacy API compatibility) and how it is then pushed from the legacy Kirkanta to the legacy API.

Therefore I have internally instructed that Kirjastot.fi technical administrators will manually delete libraries (from legacy systems) that have been deleted from Kirkanta. 

My initial (gu)estimate is that libraries will not be hidden or deleted on a regular basis. That would also be really bad for end-users who visit our websites to look up their libraries. 

Due to technical improvements it would now be possible to track removed libraries in the API (v4) but that has to be implemented into the API first.

**Comment by sjuvonen** [comment]
It should be possible to display a list of recently deleted libraries in Kirkanta (for system admins) so that we can semi-automatically see what libraries are waiting to be cleared from legacy systems as well.

**Comment by olli-suutari-jkl** [comment]
Right, on a side-note: the same issue seems to be present with visibility of parent organisations.

We changed the visibility of "Keuruun kaupunginkirjasto" to "Luonnos" in January, but it kept being visible via the v3 api. https://kirkanta.kirjastot.fi/organisation/85481

I changed our code to fetch library listing via v4 api so this is no longer an issue for us. 🤷‍♂️
