### ISSUE TITLE
v4/library endpoint only returns Finnish by default

### ISSUE THREAD

**Issue by olli-suutari-jkl** [libraries-fi/kirkanta-api#7]
If no language is specified, only the Finnish variants are returned.
Per documentation, other languages should be included as well.

https://api.kirjastot.fi/v4/library?consortium=2113&limit=1500&pretty
https://api.kirjastot.fi/v4/library?consortium=2113&limit=1500&lang=en&pretty

https://api.kirjastot.fi/v4/library?city.name=jyv%C3%A4skyl%C3%A4&pretty
https://api.kirjastot.fi/v4/library?city.name=jyv%C3%A4skyl%C3%A4&lang=en&pretty

I'm trying to generate an array of library names that includes both, fi and en variants.
Suppose I'll just create a new api call and loop the English results...

Sidenote: Would be great if it would be possible to specify multiple languages with lang parameter (eg. lang=fi, en)

**Comment by sjuvonen** [comment]
Sorry, the documentation is apparently out-of-date. 

I made the decision to drop multiple languages per query because it seemed like a technical peculiarity with little to no usage (based on server logs). It also a burden to support and limits viable implementational pathways in many ways, as it requires some thought and care to avoid performance issues.

This change has been made already back in November, see https://github.com/libraries-fi/kirkanta-api/commit/fc29f552ae149a10239853965bc74733ee6696e0

P.S. I still don't get any email notifications so I have again been forgetting to check the issue queue.

**Comment by sjuvonen** [comment]
Allowing multiple languages per result also creates a schema level requirement that cannot be changed later on, if we decided that some new field had to be translatable.
